# Generated by Django 4.2.2 on 2023-06-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_cliente_usuario_nombredeusuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='rol_user',
            new_name='rol_usuario',
        ),
    ]
