# Generated by Django 4.2.2 on 2023-06-05 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDeFantasia', models.CharField(max_length=100)),
                ('rutEmpresa', models.CharField(max_length=20)),
                ('razonSocial', models.CharField(max_length=100)),
                ('fechaIngresoCliente', models.DateField(max_length=10)),
                ('claveSII', models.CharField(max_length=100)),
                ('nombreContacto1', models.CharField(max_length=100)),
                ('telefonoContacto1', models.CharField(max_length=20)),
                ('emailContacto1', models.EmailField(max_length=100)),
                ('nombreContacto2', models.CharField(max_length=100)),
                ('telefonoContacto2', models.CharField(max_length=20)),
                ('emailContacto2', models.EmailField(max_length=100)),
                ('representanteLegal', models.CharField(max_length=100)),
                ('rutRepresentanteLegal', models.CharField(max_length=20)),
                ('banco', models.CharField(max_length=100)),
                ('tipoCuenta', models.CharField(max_length=100)),
                ('numeroCuenta', models.CharField(max_length=50)),
                ('claveSIIRepresentante', models.CharField(max_length=50)),
                ('inicioActividades', models.DateField(max_length=10)),
                ('regimenTributario', models.CharField(max_length=100)),
                ('claveCertificadoDigital', models.CharField(max_length=100)),
                ('vencimientoCertificadoDigital', models.DateField(max_length=10)),
                ('usuarioPrevired', models.CharField(max_length=100)),
                ('clavePrevired', models.CharField(max_length=100)),
                ('otroServicio', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
